services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: 123456fiap
      POSTGRES_DB: oficina_mecanica
    ports:
      - '5433:5432'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U oficina -d oficina_mecanica']
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build: .
    ports:
      - '3000:3000'
    environment:
      JWT_SECRET: troque-este-jwt-secret-com-mais-de-16-caracteres
      JWT_EXPIRES_IN: 1h
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: oficina
      POSTGRES_PASSWORD: 123456fiap
      POSTGRES_DB: oficina_mecanica
      POSTGRES_SSL: 0
    depends_on:
      postgres:
        condition: service_healthy
